import WrappedProviders from '@/components/providers/wrapped-providers'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const jetbrainsMono = localFont({
  variable: '--font-mono',
  src: [
    {
      path: '../fonts/JetBrainsMono-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../fonts/JetBrainsMono-ExtraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../fonts/JetBrainsMono-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/JetBrainsMono-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/JetBrainsMono-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/JetBrainsMono-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../fonts/JetBrainsMono-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/JetBrainsMono-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn('h-full', 'antialiased', 'font-mono', jetbrainsMono.variable)}>
      <body className="flex min-h-full flex-col">
        <WrappedProviders>{children}</WrappedProviders>
      </body>
    </html>
  )
}
